# Generated by Django 3.1.7 on 2022-05-08 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220508_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
