# Generated by Django 4.0.4 on 2022-05-09 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='system_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
