# Generated by Django 4.0.4 on 2022-06-01 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='task',
            name='system_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
